# Generated by Django 3.2.11 on 2022-01-30 01:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=256)),
                ('arrival_time', models.DateTimeField()),
                ('passenger_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('confirmed', 'confirmed'), ('open', 'open')], default='open', max_length=32)),
                ('special_request', models.CharField(blank=True, default='', max_length=256)),
                ('special_vehicle_type', models.CharField(blank=True, default='', max_length=256)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('female', 'female'), ('male', 'male')], default='male', max_length=32)),
                ('is_driver', models.BooleanField(blank=True, default=False, null=True)),
                ('full_name', models.CharField(blank=True, max_length=128, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=256, null=True)),
                ('plate_num', models.CharField(blank=True, max_length=256, null=True)),
                ('max_passenger', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('special_vehicle_info', models.CharField(blank=True, max_length=256, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_passenger', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='login.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='sharer',
            field=models.ManyToManyField(blank=True, related_name='sharer', to='login.User'),
        ),
    ]
