# Generated by Django 4.0.1 on 2022-01-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('confirmed', 'confirmed')], default='open', max_length=32),
        ),
    ]
